CREATE ROLE lab_user WITH LOGIN PASSWORD 'lab_pass' CREATEDB NOSUPERUSER NOCREATEROLE;
-- CREATE DATABASE labs_db OWNER lab_user;
-- ALTER SCHEMA public OWNER TO lab_user;
-- GRANT CONNECT ON DATABASE TU_BASE TO lab_user;
-- GRANT USAGE, CREATE ON SCHEMA public TO lab_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
--   GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO lab_user;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public
--   GRANT USAGE, SELECT ON SEQUENCES TO lab_user;